### ISSUE TITLE
Is there any scripts to preprocess the NEMSIS data?

### ISSUE THREAD

**Issue by xueren-ge** [LENSS/EMSAssist#1]
Hi, it's a great work. And I was wondering if there's any python scripts to preprocess the NEMSIS data? For example concatenating all tables together and extracting important information (protocols, signs&symptoms, medications, procedures) into one complete table. Because the dataset is very large. I appreciate it very much if the script is shareable. Thanks!

**Comment by rstoleru** [comment]
Hi. Was your question addressed by the first author of the paper?

**Comment by xueren-ge** [comment]
No, I didn't get responses from the author. I'm still working on preprocessing NEMSIS by myself.

**Comment by rstoleru** [comment]
ok. I just asked him the second time to get in touch with you. I asked him a few weeks ago, but he is very busy.

**Comment by liuyibox** [comment]
Hi @xueren-ge, Sorry, I did not see this issue earlier. I just added myself as a watcher to all activities.

Scripts are added for preprocessing signs and symptoms, and medication. Protocol scripts are old and messed up with other irrelevant scripts on my side. I don't have scripts for procedures. From what I can see, protocol and procedure preprocessing is very similar to medication preprocessing. If you have questions regarding to NEMSIS preprocessing, we'd like to help.

I'm closing this issue for now, and you can re-open it later if you have questions about the scripts.
